// قاعدة المعرفة: مصدر واحد للمساعد ومركز المساعدة والأدلة. راجعها المكتب قبل الإطلاق.
(function(){
const E=(id,cat,k,t,a,f)=>({id,cat,k,t,a,f:f||{ar:[],en:[]}});
const entries=[
E('hello','',['مرحبا','اهلا','السلام','صباح','مساء','hello','hi','hey'],{ar:'أهلًا بك',en:'Welcome'},
{ar:'أهلًا بك في المؤسسة القانونية الدولية I.L.F. أستطيع التعريف بالمكتب وخدماته، وشرح الخطوات العامة لمسألتك وما تجهّزه من مستندات، وتحويلك لمحامٍ. ما الذي تحتاجه؟',en:'Welcome to I.L.F International Legal Firm. I can introduce the firm, explain general steps and the documents to prepare, and connect you with a lawyer. How can I help?'}),
E('firm','',['المكتب','المؤسسه','مؤسسه','عنكم','من انتم','تاسست','about','firm','who are you','founded'],{ar:'عن المؤسسة',en:'About the firm'},
{ar:'المؤسسة القانونية الدولية I.L.F مؤسسة محاماة في مصر الجديدة بالقاهرة، تأسست عام 2004 على يد د. هشام الحناوي وشركاه. تعمل في تأسيس الشركات والعقود الدولية والتحكيم ومنازعات الاستثمار والتقاضي، ولديها فريق يقدّم الاستشارات بتعاقدات شهرية أو سنوية.',en:'I.L.F International Legal Firm is a law firm in Heliopolis, Cairo, founded in 2004 by Dr. Hesham El-Henawy and partners. It works on company formation, international contracts, arbitration, investment disputes and litigation, with a team offering monthly or yearly retainers.'}),
E('founder','',['هشام','الحناوي','المؤسس','الدكتور','دكتور','founder','henawy','hesham','دكتوراه'],{ar:'المؤسس',en:'The founder'},
{ar:'د. هشام عبدالله الحناوي: دكتوراه القانون الدولي العام (جامعة القاهرة 2016)، وماجستير في العقود الدولية والإدارية (طنطا 2005)، وليسانس حقوق الإسكندرية (2002). محامٍ بالنقض والإدارية العليا والدستورية العليا، ومحكّم بالمركز المصري للتحكيم التجاري الدولي.',en:'Dr. Hesham Abdullah El-Henawy: Ph.D. in Public International Law (Cairo University, 2016), LL.M. in international and administrative contracts (Tanta, 2005), LL.B. Alexandria (2002). Advocate before the Courts of Cassation, Supreme Administrative and Supreme Constitutional Courts, and arbitrator at the Egyptian Centre for International Commercial Arbitration.'}),
E('services','',['خدمات','تخصص','مجالات','تقدمون','تعملون','services','practice','specialt','what do you do'],{ar:'الخدمات',en:'Services'},
{ar:'خدمات المؤسسة: تأسيس الشركات والاستحواذ، العقود المحلية والدولية (BOT/BOO/FIDIC)، التحكيم، الاستثمار، الأعمال البنكية، التقاضي وتنفيذ الأحكام، التقنية والملكية الفكرية، والاستشارات الدورية. اذكر لي مسألتك وأحدد لك الأقرب.',en:'Services: company formation and M&A, local and international contracts (BOT/BOO/FIDIC), arbitration, investment, banking, litigation and enforcement, technology and IP, and retainer advisory. Tell me your matter and I will point to the closest one.'}),
E('contact','',['تواصل','اتصل','رقم','هاتف','واتساب','عنوان','فين','موقع','ايميل','بريد','contact','phone','whatsapp','address','where','email'],{ar:'التواصل',en:'Contact'},
{ar:'العنوان: 99 امتداد شارع هارون الرشيد، أمام المدرسة الإنجليزية، مصر الجديدة، القاهرة. الهاتف وواتساب: 01220778988. البريد: hhenawy2@yahoo.com.',en:'Address: 99 Haroun El-Rashid St. Extension, opposite the English School, Heliopolis, Cairo. Phone/WhatsApp: 01220778988. Email: hhenawy2@yahoo.com.'}),
E('consult','',['استشاره','موعد','احجز','حجز','مقابله','consult','appointment','book','meeting'],{ar:'طلب استشارة',en:'Request a consultation'},
{ar:'لطلب استشارة: املأ نموذج التواصل أو راسل المكتب على واتساب. جهّز ملخصًا قصيرًا للمسألة والمستندات الأساسية وأي مواعيد قريبة. لا ترسل كلمات مرور أو بيانات مالية عبر الموقع.',en:'To request a consultation, fill in the contact form or message the firm on WhatsApp. Prepare a short summary, the key documents and any upcoming deadlines. Never send passwords or financial credentials through the site.'}),
E('fees','',['اتعاب','سعر','تكلفه','كم','مصاريف','fee','cost','price','how much'],{ar:'الأتعاب',en:'Fees'},
{ar:'الأتعاب تُحدَّد بعد دراسة المسألة ونطاق العمل، ولا أستطيع تحديد رقم هنا. تقدّم المؤسسة أيضًا تعاقدات شهرية أو سنوية للشركات. اطلب استشارة ليُبلغك المكتب بالتفاصيل.',en:'Fees are set after the matter and scope are reviewed, so I cannot quote a figure. The firm also offers monthly or yearly retainers for companies. Request a consultation for details.'}),
E('company','corp',['شركه','شركات','تاسيس','اسس','تسجيل شركه','سجل تجاري','مساهمه','محدوده','توصيه','company','incorporat','setup','set up','llc','startup','register a'],{ar:'تأسيس شركة',en:'Forming a company'},
{ar:'الخطوات العامة لتأسيس شركة في مصر: 1) اختيار الشكل القانوني (مساهمة، ذات مسؤولية محدودة، توصية، شركة أشخاص...) وتحديد النشاط ورأس المال. 2) حجز الاسم التجاري. 3) إعداد عقد التأسيس والنظام الأساسي. 4) اعتماد العقد لدى الجهة المختصة (مثل الهيئة العامة للاستثمار حسب النشاط). 5) القيد في السجل التجاري واستخراج البطاقة الضريبية. 6) التسجيل في التأمينات وفتح حساب بنكي. الاشتراطات تتغير، ويؤكد محامي المؤسسة المطلوب لنشاطك تحديدًا. المرجع العام: قانون الشركات 159 لسنة 1981 وقانون الاستثمار 72 لسنة 2017.',en:'General steps to form a company in Egypt: 1) choose the legal form (joint-stock, LLC, partnership...), activity and capital; 2) reserve the trade name; 3) draft the articles and bylaws; 4) have the contract approved by the competent authority (e.g. GAFI depending on activity); 5) commercial register and tax card; 6) social insurance and a bank account. Requirements change, so the firm confirms what applies to your activity. General references: Companies Law 159/1981 and Investment Law 72/2017.'},
{ar:['ما نشاط الشركة المقترح؟','كم عدد الشركاء وهل فيهم أجانب؟'],en:['What is the intended activity?','How many partners, and are any foreign?']}),
E('contract','contracts',['عقد','عقود','اتفاقيه','صياغه','بند','شرط جزايي','مراجعه عقد','contract','agreement','draft','clause'],{ar:'العقود',en:'Contracts'},
{ar:'العقد التجاري الجيد يحدد غالبًا: أطراف العقد وصفاتهم، محل العقد بدقة، الثمن وطريقة السداد ومواعيده، مدة العقد، التزامات كل طرف، التسليم والقبول، الشرط الجزائي والمسؤولية، القوة القاهرة، السرية، الإنهاء وآثاره، القانون الواجب التطبيق وطريقة فض المنازعات (قضاء أم تحكيم)، وعناوين الإخطارات. يصيغ المكتب العقود المحلية والدولية، منها BOT وBOO وعقود الفيديك ونقل التكنولوجيا.',en:'A sound commercial contract usually fixes: the parties, the exact subject, price and payment terms, duration, each side’s obligations, delivery and acceptance, penalties and liability, force majeure, confidentiality, termination, governing law and dispute resolution (courts or arbitration), and notice addresses. The firm drafts local and international contracts including BOT, BOO, FIDIC and technology transfer.'},
{ar:['هل العقد مكتوب بالفعل أم تريد صياغته؟','ما قيمة الصفقة ومدتها؟'],en:['Is there a draft already, or do you need one drafted?','What is the deal value and duration?']}),
E('arbitration','arb',['تحكيم','محكم','مركز القاهره الاقليمي','شرط التحكيم','arbitrat','tribunal','crcica'],{ar:'التحكيم',en:'Arbitration'},
{ar:'التحكيم طريق لفض النزاع خارج المحاكم يقوم على اتفاق مكتوب (شرط في العقد أو اتفاق لاحق). من مزاياه المعتادة: السرية، واختيار المحكّمين، ومرونة الإجراءات، وسرعة نسبية. وله حدود: لا يصح إلا بوجود اتفاق، وتكلفته قد تكون مرتفعة، والطعن على الأحكام محدود. المرجع العام: قانون التحكيم 27 لسنة 1994. للمؤسسة خبرة في قضايا مركز القاهرة الإقليمي للتحكيم التجاري الدولي.',en:'Arbitration resolves disputes outside the courts based on a written agreement (a contract clause or later submission). Usual advantages: confidentiality, choice of arbitrators, flexible procedure and relative speed. Limits: it needs an agreement, can be costly, and challenges to awards are narrow. General reference: Arbitration Law 27/1994. The firm has experience in cases before the Cairo Regional Centre for International Commercial Arbitration.'},
{ar:['هل يوجد شرط تحكيم في العقد؟','ما قيمة النزاع تقريبًا؟'],en:['Does the contract contain an arbitration clause?','Roughly what is the amount in dispute?']}),
E('investment','inv',['استثمار','مستثمر','هيئه الاستثمار','منازعات استثمار','لجنه','investment','investor','gafi'],{ar:'الاستثمار',en:'Investment'},
{ar:'يتولى المكتب منازعات الاستثمار والتفاوض والوساطة، ومنها الدعاوى أمام الهيئة العامة للاستثمار واللجنة الوزارية لفض منازعات الاستثمار. جهّز: قرار أو ترخيص الجهة، والعقد مع الجهة المقابلة، والمراسلات الرسمية، وبيان الخلاف وقيمته. المرجع العام: قانون الاستثمار 72 لسنة 2017.',en:'The firm handles investment disputes, negotiation and mediation, including matters before GAFI and the ministerial committee for investment disputes. Prepare: the authority’s decision or licence, the contract with the counterparty, official correspondence and a statement of the dispute and its value. General reference: Investment Law 72/2017.'}),
E('banking','bank',['بنك','بنكي','خطاب ضمان','اعتماد مستندي','قرض','بورصه','اكتتاب','رقابه ماليه','bank','guarantee','letter of credit','credit','stock','ipo','fra'],{ar:'الأعمال البنكية وسوق المال',en:'Banking & capital markets'},
{ar:'خطاب الضمان تعهد من البنك بدفع مبلغ للمستفيد إذا أخلّ العميل بالتزامه. والاعتماد المستندي تعهد من البنك بالدفع للبائع مقابل مستندات شحن مطابقة للشروط. يقدّم المكتب استشارات في الضمانات والاعتمادات وإجراءات البورصة والرقابة المالية وطرح الأسهم للاكتتاب العام. المرجع العام: قانون البنك المركزي والجهاز المصرفي 194 لسنة 2020.',en:'A letter of guarantee is the bank’s undertaking to pay the beneficiary if the customer defaults. A documentary credit is the bank’s undertaking to pay the seller against shipping documents that comply with its terms. The firm advises on guarantees, credits, stock exchange and FRA procedures and public offerings. General reference: Central Bank and Banking Sector Law 194/2020.'}),
E('litigation','lit',['قضيه','دعوي','محكمه','جلسه','حكم','تنفيذ','استئناف','نقض','عمال','فصل','عامل','اجور','case','lawsuit','court','hearing','judgment','enforce','appeal','labor','labour','dismiss'],{ar:'التقاضي وتنفيذ الأحكام',en:'Litigation & enforcement'},
{ar:'يتولى المكتب القضايا المدنية والاقتصادية والتجارية والعمالية أمام جميع درجات التقاضي، وتنفيذ الأحكام. أهم ما يجب فعله فورًا: لا تتأخر لأن المواعيد القانونية صارمة وقد يسقط الحق بفواتها، واجمع كل المستندات وتواريخ الجلسات والإعلانات. تنفيذ الحكم يتطلب عادةً حكمًا نهائيًا مذيّلًا بالصيغة التنفيذية. هذه معلومات عامة والتقدير النهائي لمحامٍ بعد الاطلاع على الأوراق.',en:'The firm handles civil, economic, commercial and labour cases at all court levels, plus enforcement of judgments. Most urgent: do not delay, as legal deadlines are strict and a right can be lost by missing them; gather all documents, hearing dates and notices. Enforcement normally needs a final judgment bearing the executory formula. This is general information; a lawyer decides after seeing the papers.'},
{ar:['ما موعد أقرب جلسة أو إعلان؟','هل صدر حكم بالفعل؟'],en:['When is the nearest hearing or notice?','Has a judgment already been issued?']}),
E('tech','tech',['علامه تجاريه','ملكيه فكريه','وكاله تجاريه','سيبراني','ذكاء اصطناعي','بيانات شخصيه','تحول رقمي','برمجه','trademark','intellectual','ip','cyber','ai','data protection','privacy','software','digital'],{ar:'التقنية والملكية الفكرية',en:'Technology & IP'},
{ar:'يتناول المكتب عقود التقنية ونقل التكنولوجيا، والتحول الرقمي، والذكاء الاصطناعي والأمن السيبراني، وتسجيل العلامات التجارية والوكالات التجارية. في العلامات: يُنصح بالبحث المسبق ثم تقديم الطلب فالفحص والنشر وفترة الاعتراض. مراجع عامة: قانون حماية الملكية الفكرية 82 لسنة 2002، وقانون حماية البيانات الشخصية 151 لسنة 2020، وقانون مكافحة جرائم تقنية المعلومات 175 لسنة 2018.',en:'The firm covers technology contracts and technology transfer, digital transformation, AI and cybersecurity, and trademark and commercial agency registration. For trademarks: search first, then file, examination, publication and an opposition period. General references: IP Law 82/2002, Personal Data Protection Law 151/2020 and Anti-Cyber and IT Crimes Law 175/2018.'}),
E('retainer','ret',['تعاقد شهري','سنوي','دوره','استشارات دوريه','قسم قانوني','retainer','monthly','yearly','in-house','outsourc'],{ar:'الاستشارات الدورية',en:'Retainer advisory'},
{ar:'للشركات: تعاقد شهري أو سنوي مع فريق المؤسسة، ودعم قانوني إلكتروني وهاتفي، ويمكن تخصيص عضو من الفريق بدوام جزئي أو كلي تحت إشراف المؤسسة اليومي.',en:'For companies: a monthly or yearly engagement with the firm’s team, online and phone legal support, and a team member can be assigned part- or full-time under the firm’s daily supervision.'}),
E('urgent','',['عاجل','طارئ','النهارده','بكره','غدا','قبض','محضر','urgent','emergency','arrest','tomorrow','today'],{ar:'حالة عاجلة',en:'Urgent matter'},
{ar:'إن كان الأمر عاجلًا (جلسة قريبة، إعلان بميعاد، توقيف) فلا تنتظر الرد الآلي: اتصل بالمكتب الآن على 01220778988 أو راسله على واتساب وأرسل ما لديك من أوراق.',en:'If it is urgent (a near hearing, a notice with a deadline, detention), do not wait for an automated reply: call the firm now on 01220778988 or message on WhatsApp with whatever papers you have.'}),
E('privacy','',['خصوصيه','سريه','بياناتي','امان','privacy','confidential','secure'],{ar:'الخصوصية',en:'Privacy'},
{ar:'لا ترسل كلمات مرور أو بيانات بنكية أو صور هوية عبر المحادثة. المساعد ليس محاميًا ولا ينشئ علاقة موكّل ومحامٍ. الردود المحلية تُحسب داخل متصفحك، وإرسال رسائلك لخدمة المساعد الذكي لا يتم إلا بموافقتك.',en:'Do not send passwords, bank details or ID photos in chat. The assistant is not a lawyer and creates no attorney-client relationship. Local answers are computed in your browser; your messages go to the AI service only if you consent.'})
];
const DOCS={corp:{ar:['صور هويات الشركاء أو المساهمين','الشكل القانوني والنشاط المقترح','رأس المال وتوزيع الحصص','عنوان المقر ومستند ملكيته أو إيجاره'],en:['Partners’/shareholders’ IDs','Proposed legal form and activity','Capital and share split','Premises address and title/lease']},
contracts:{ar:['مسودة العقد أو الاتفاق المبدئي','بيانات الأطراف','المراسلات السابقة','الشروط التجارية: السعر والمدة والتسليم'],en:['Draft contract or term sheet','Party details','Prior correspondence','Commercial terms: price, term, delivery']},
arb:{ar:['العقد وشرط التحكيم','المراسلات بين الأطراف','مستندات إثبات الحق','أي إخطارات رسمية'],en:['Contract and arbitration clause','Correspondence between parties','Evidence of the claim','Any formal notices']},
inv:{ar:['قرار أو ترخيص الجهة','العقد مع الجهة المقابلة','المراسلات الرسمية','بيان الخلاف وقيمته'],en:['Authority decision or licence','Contract with counterparty','Official correspondence','Statement of dispute and value']},
bank:{ar:['صورة الضمان أو الاعتماد','العقد الأساسي','مكاتبات البنك','تواريخ الاستحقاق'],en:['Copy of guarantee or credit','Underlying contract','Bank correspondence','Due dates']},
lit:{ar:['صحف الدعاوى والأحكام','العقود والمستندات','تواريخ الجلسات والإعلانات','التوكيلات إن وُجدت'],en:['Pleadings and judgments','Contracts and documents','Hearing dates and notices','Powers of attorney, if any']},
tech:{ar:['العقد أو الاتفاقية التقنية','وصف المنتج أو الخدمة','طريقة التعامل مع البيانات الشخصية','مستندات الملكية الفكرية'],en:['Technology contract','Product/service description','How personal data is handled','IP documents']},
ret:{ar:['حجم الأعمال القانونية الشهرية','عقود الشركة الأساسية','هيكل الإدارة','نوع الدعم المطلوب'],en:['Monthly legal workload','Core company contracts','Management structure','Support needed']}};
const ROAD={ar:['تحديد الشكل القانوني والنشاط ورأس المال','حجز الاسم التجاري','إعداد عقد التأسيس والنظام الأساسي','اعتماد العقد لدى الجهة المختصة','القيد في السجل التجاري','استخراج البطاقة الضريبية والتسجيل الضريبي المناسب','التسجيل في التأمينات الاجتماعية','فتح الحساب البنكي وإيداع رأس المال'],en:['Choose legal form, activity and capital','Reserve the trade name','Draft articles and bylaws','Approval by the competent authority','Commercial register entry','Tax card and applicable tax registration','Social insurance registration','Open the bank account and deposit capital']};
const CCHK={ar:['أطراف العقد وصفاتهم','محل العقد بدقة','الثمن وطريقة السداد','المدة وشروط التجديد','التزامات كل طرف','التسليم والقبول','الشرط الجزائي والمسؤولية','القوة القاهرة','السرية','الإنهاء وآثاره','القانون الواجب وفض المنازعات','عناوين الإخطارات'],en:['Parties and capacities','Exact subject','Price and payment','Term and renewal','Each side’s obligations','Delivery and acceptance','Penalty and liability','Force majeure','Confidentiality','Termination and effects','Governing law and disputes','Notice addresses']};
const GLOSS=[['عقد التأسيس','Memorandum of association','الاتفاق المكتوب بين المؤسسين الذي تنشأ به الشركة.','The written agreement among founders that creates the company.'],['النظام الأساسي','Articles/bylaws','القواعد الداخلية لإدارة الشركة وحقوق الشركاء.','Internal rules for running the company and partners’ rights.'],['السجل التجاري','Commercial register','قيد رسمي للتاجر أو الشركة يثبت وجودها ونشاطها.','Official entry proving a trader’s or company’s existence and activity.'],['شرط التحكيم','Arbitration clause','بند في العقد يحيل النزاع إلى التحكيم بدل القضاء.','A contract term sending disputes to arbitration instead of courts.'],['الصيغة التنفيذية','Executory formula','عبارة تُذيَّل بها الأحكام والسندات لتصبح قابلة للتنفيذ جبرًا.','A formula appended to judgments or instruments making them enforceable.'],['خطاب الضمان','Letter of guarantee','تعهد من البنك بدفع مبلغ للمستفيد عند إخلال العميل.','A bank undertaking to pay the beneficiary if the customer defaults.'],['الاعتماد المستندي','Documentary credit','تعهد من البنك بالدفع للبائع مقابل مستندات مطابقة للشروط.','A bank undertaking to pay the seller against compliant documents.'],['BOT','Build-Operate-Transfer','بناء وتشغيل ثم نقل ملكية المشروع للجهة المتعاقدة.','Build, operate, then transfer the project to the contracting authority.'],['FIDIC','FIDIC','شروط تعاقد نموذجية دولية لمشروعات الهندسة والإنشاء.','International standard conditions of contract for engineering and construction.'],['القوة القاهرة','Force majeure','حدث خارج الإرادة يمنع تنفيذ الالتزام ولا يمكن توقعه أو دفعه.','An unforeseeable, unavoidable event beyond control that prevents performance.'],['الشرط الجزائي','Penalty clause','اتفاق مسبق على تعويض عند الإخلال بالعقد.','Pre-agreed compensation for breach.']];
const norm=s=>(s||'').toLowerCase().replace(/[\u064B-\u0652\u0640]/g,'').replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^\p{L}\p{N}\s]/gu,' ');
function answer(text,L){const q=norm(text),w=new Set(q.split(/\s+/));let best=null,bs=0;
 entries.forEach(e=>{let s=0;e.k.forEach(k=>{const n=norm(k);if(n.length<=3?w.has(n):q.includes(n))s+=n.length>3?2+(n.length>6?1:0):1});if(e.id==='urgent'&&s)s+=3;if(s>bs){bs=s;best=e}});
 if(!best||bs<2)return null;
 return {e:best,x:best.a[L],f:(best.f[L]||[]),cat:best.cat}}
window.KB={entries,DOCS,ROAD,CCHK,GLOSS,answer};
})();
