(function(){
document.documentElement.classList.add('js');
const {SITE,PHOTOS,AREAS,TIMELINE,MEMBERSHIPS,ROLES,FORMED,ADVISED,CLIENTS}=C,K=KB,cfg=window.CONFIG||{};
const NAV=[['',{ar:'الرئيسية',en:'Home'}],['about',{ar:'عن المؤسسة',en:'About'}],['practice-areas',{ar:'الخدمات',en:'Services'}],['team',{ar:'المؤسس',en:'Founder'}],['experience',{ar:'الخبرات',en:'Experience'}],['clients',{ar:'العملاء',en:'Clients'}],['help',{ar:'مركز المساعدة',en:'Help centre'}],['ai-assistant',{ar:'المساعد الذكي',en:'AI assistant'}],['insights',{ar:'أدلة ومقالات',en:'Guides'}],['contact',{ar:'تواصل',en:'Contact'}]];
let L=(function(){let q=null;try{q=new URLSearchParams(location.search).get('lang')}catch(e){}if(q==='ar'||q==='en'){try{localStorage.setItem('lang',q)}catch(e){}return q}let s=null;try{s=localStorage.getItem('lang')}catch(e){}return s==='en'?'en':'ar'})();
const t=b=>b[L],x=(a,e)=>L==='ar'?a:e,page=document.body.dataset.page,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const red=matchMedia('(prefers-reduced-motion: reduce)').matches,uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now());
const href=p=>p?p+'.html':'index.html',WA=txt=>`https://wa.me/${SITE.wa}${txt?'?text='+encodeURIComponent(txt):''}`;
const CO_EN={"Berida Enregia (فرع الشركة الإيطالية)": "Berida Enregia (branch of the Italian company)", "العربية الأحلام للسياحة والفنادق": "Al-Arabiya Al-Ahlam for Tourism and Hotels", "المجموعة الدولية للخدمات القانونية (بالشراكة مع P.F.E.)": "International Group for Legal Services (in partnership with P.F.E.)", "Khalilof للبرمجة ونظم المعلومات": "Khalilof for Software and Information Systems", "Flow Trading (وكيل Playmobil الألمانية)": "Flow Trading (agent of Germany’s Playmobil)", "Rainbow للاستيراد والتصدير": "Rainbow for Import and Export", "Rafhia للتجارة والتوزيع": "Rafhia for Trading and Distribution", "Internaut للملاحة البحرية": "Internaut for Maritime Navigation", "مجموعة أبل للإعلان والدعاية": "Apple Group for Advertising and Publicity", "Geam للأجهزة الكهربائية المنزلية الصغيرة": "Geam for Small Household Appliances", "تحويل الشركة المصرية لخدمات الاتصالات إلى شركة مساهمة": "Conversion of the Egyptian telecommunications services company into a joint-stock company", "إيكو طاقة للطاقة المتجددة": "Eco Taqa for Renewable Energy", "مجموعة دلمار للاستثمار الصناعي والزراعي": "Delmar Group for Industrial and Agricultural Investment", "الشركة المصرية السعودية للاستثمار العقاري": "Egyptian Saudi Company for Real Estate Investment", "مجموعة أي سي تي لخدمات الأمن السيبراني": "ICT Group for Cybersecurity Services", "بلدين جي مصر للاستثمار الزراعي": "Baldin G Egypt for Agricultural Investment", "Sustaincubator للطاقة المتجددة والري الحديث": "Sustaincubator for Renewable Energy and Modern Irrigation", "معمل الفيل الطائر (Yaoota)": "The Flying Elephant Lab (Yaoota)", "مجموعة دلمار": "Delmar Group", "Idea for Life للتنمية المستدامة": "Idea for Life for Sustainable Development", "جازفيل لتعبئة الغاز": "Gazville for Gas Filling", "غاز السويس": "Suez Gas", "فرست جاز": "First Gas"};const co=s=>L==="en"?(CO_EN[s]||s):s;
const sec=(c,h,b)=>`<section class="sec ${c}"><div class="wrap">${h?`<h2 class="rv">${h}</h2>`:''}${b}</div></section>`;
const ph=(h,p)=>`<div class="ph"><div class="wrap"><h1>${h}</h1>${p?`<p>${p}</p>`:''}</div></div>`;
const mosaic=()=>`<div class="mosaic">${PHOTOS.map((p,k)=>`<button class="mz rv" data-k="${k}" aria-label="${t(p.cap)}"><img src="${p.src}" alt="${t(p.cap)}" loading="lazy"><span>${t(p.cap)}</span></button>`).join('')}</div>`;
const ul=a=>`<ul class="ul">${a.map(i=>`<li>${i}</li>`).join('')}</ul>`;
const tl=()=>`<ol class="tl">${TIMELINE.map(e=>`<li class="rv"><b>${e.y}</b><span>${t(e.t)}</span></li>`).join('')}</ol>`;
const cta=()=>`<div class="cta"><div class="wrap rv"><h2>${x('لديك مسألة قانونية؟','Have a legal matter?')}</h2><p>${x('اسأل المساعد أولًا أو اطلب استشارة مباشرة من المكتب.','Ask the assistant first or request a consultation directly.')}</p><div class="row" style="justify-content:center"><a class="btn" href="contact.html">${x('اطلب استشارة','Request a consultation')}</a><button class="btn ghost" data-open-ai>${x('اسأل المساعد','Ask the assistant')}</button></div></div></div>`;
const flips=()=>`<div class="flips">${AREAS.map((a,i)=>`<div class="flip rv" tabindex="0" role="button" aria-label="${t(a.t)}"><div class="fi"><div class="ff"><span class="ico"><b>${i+1}</b></span><div><h3>${t(a.t)}</h3><small>${t(a.s)}</small></div></div><div class="fb"><ul>${a.d.map(d=>`<li>${t(d)}</li>`).join('')}</ul><a href="contact.html?cat=${a.id}">${x('اطلب استشارة في هذا المجال','Request a consultation')}</a></div></div></div>`).join('')}</div>`;
const gallery=()=>`<div class="gal" tabindex="0" aria-roledescription="carousel" aria-label="${x('صور المؤسس','Founder photos')}"><div class="stage" dir="ltr">${PHOTOS.map((p,k)=>`<button class="slide" data-k="${k}" aria-label="${t(p.cap)}"><img src="${p.src}" alt="${t(p.cap)}" loading="lazy"></button>`).join('')}</div><div class="gc"><button data-g="-1" aria-label="${x('السابقة','Previous')}">‹</button><span id="cap"></span><button data-g="1" aria-label="${x('التالية','Next')}">›</button><button class="sm" id="play" aria-pressed="false"></button></div><div class="dots">${PHOTOS.map(()=>'<i></i>').join('')}</div></div>`;
const ringHTML=()=>`<div class="ringw" aria-label="${x('عملاء المؤسسة','Our clients')}"><div class="ring">${CLIENTS.map(c=>`<button data-id="${c.id}" aria-label="${t(c.n)}"><img src="${c.logo}" alt="${t(c.n)}"></button>`).join('')}</div></div><div class="spin"><button data-spin="-1" aria-label="${x('السابق','Previous')}">‹</button><button data-spin="1" aria-label="${x('التالي','Next')}">›</button></div>`;
const logos=()=>`<ul class="logos">${CLIENTS.map(c=>`<li><button data-id="${c.id}" aria-label="${t(c.n)}"><img src="${c.logo}" alt="${t(c.n)}" loading="lazy"></button></li>`).join('')}</ul>`;
const yrs=new Date().getFullYear()-2004,nco=FORMED.reduce((s,f)=>s+f.n.length,0);
const guide=id=>{const e=K.entries.find(e=>e.id===id);return `<details class="q rv"><summary>${t(e.t)}</summary><p>${e.a[L]}</p><p class="note">${x('دليل تعريفي عام وليس استشارة قانونية.','General guide, not legal advice.')}</p></details>`};
const docsList=()=>AREAS.map(a=>`<details class="q"><summary>${t(a.t)}</summary>${ul(K.DOCS[a.id][L])}</details>`).join('');
// ---------- views ----------
const V={
home:()=>`<header class="hero"><canvas id="c3d" aria-hidden="true"></canvas><div class="wrap hg"><div><h1>${x('منذ 2004: عقود محكمة، وشركات تتأسس على أساس سليم','Since 2004: tight contracts, and companies built on solid ground')}</h1><p>${x('مؤسسة قانونية بقيادة د. هشام الحناوي، محامٍ بالنقض ومحكّم. تأسيس الشركات، العقود الدولية، التحكيم، ومنازعات الاستثمار، ومساعد ذكي يرشدك قبل أن تتصل.','A law firm led by Dr. Hesham El-Henawy, advocate before the Court of Cassation and arbitrator. Company formation, international contracts, arbitration, investment disputes, and an AI assistant that guides you before you call.')}</p><div class="row"><a class="btn" href="practice-areas.html">${x('استكشف خبراتنا','Explore our expertise')}</a><button class="btn ghost" data-open-ai>${x('تعرّف على مساعدنا الذكي','Meet our AI assistant')}</button></div></div>
 <figure class="hp tilt"><img src="${PHOTOS[0].src}" alt="${t(PHOTOS[0].cap)}"><span class="fl f1">${x('دكتوراه القانون الدولي','Ph.D. International Law')}</span><span class="fl f2">${x('محكّم تجاري دولي','International arbitrator')}</span><span class="fl f3">${x('القاهرة منذ 2004','Cairo since 2004')}</span></figure></div></header>
 <div class="stats"><div class="wrap"><div><b class="num" data-to="${yrs}">${yrs}</b><small>${x('سنة منذ تأسيس المؤسسة','years since founding')}</small></div><div><b class="num" data-to="${nco}">${nco}</b><small>${x('شركة تولّى المكتب تأسيسها (وفق بيانات المؤسسة)','companies formed by the firm (per firm records)')}</small></div><div><b class="num" data-to="${AREAS.length}">${AREAS.length}</b><small>${x('مجالات قانونية','practice areas')}</small></div><div><b class="num" data-to="${MEMBERSHIPS.length}">${MEMBERSHIPS.length}</b><small>${x('عضويات مهنية للمؤسس','professional memberships')}</small></div></div></div>`
 +sec('',x('المؤسس','The founder'),`<div class="split"><div class="rv"><h3>${t(SITE.founder)}</h3><p>${x('دكتوراه في القانون الدولي العام من جامعة القاهرة، وماجستير في العقود الدولية والإدارية (BOT/BOO/FIDIC)، ومحامٍ بالنقض والإدارية العليا والدستورية العليا، ومحكّم بالمركز المصري للتحكيم التجاري الدولي.','Ph.D. in Public International Law from Cairo University, LL.M. in international and administrative contracts (BOT/BOO/FIDIC), advocate before the Courts of Cassation, Supreme Administrative and Supreme Constitutional Courts, and arbitrator at the Egyptian Centre for International Commercial Arbitration.')}</p><a class="more" href="team.html">${x('الملف المهني','Full profile')}</a></div>${gallery()}</div>`)
 +sec('alt',x('الخدمات القانونية','Practice areas'),`<p class="rv">${x('مرّر المؤشر أو اضغط على أي كارت لرؤية التفاصيل.','Hover or tap a card for details.')}</p>${flips()}`)
 +sec('dk',x('عملاء المؤسسة','Our clients'),`<p>${x('اسحب الحلقة أو اضغط على شعار لعرض التفاصيل.','Drag the ring or select a logo for details.')}</p>${ringHTML()}`)
 +sec('',x('محطات مهنية','Milestones'),tl())
 +sec('dk',x('كيف تبدأ؟','How to start'),`<ol class="steps" style="padding:0"><li class="rv"><h3>${x('اسأل المساعد','Ask the assistant')}</h3>${x('اشرح مسألتك واعرف المجال المناسب والمستندات المطلوبة.','Describe your matter and learn the relevant area and documents.')}</li><li class="rv"><h3>${x('استخدم مركز المساعدة','Use the help centre')}</h3>${x('قوائم تحقق وخارطة تأسيس شركة ومسرد مصطلحات.','Checklists, a company-formation roadmap and a glossary.')}</li><li class="rv"><h3>${x('اطلب استشارة','Request a consultation')}</h3>${x('يتواصل معك المكتب بعد مراجعة طلبك.','The firm contacts you after reviewing your request.')}</li></ol>`)
 +sec('alt',x('أدلة سريعة','Quick guides'),guide('company')+guide('contract')+guide('arbitration')+`<a class="more" href="insights.html">${x('كل الأدلة','All guides')}</a>`)+cta(),
about:()=>ph(x('عن المؤسسة','About the firm'),x('مؤسسة قانونية في مصر الجديدة، تأسست عام 2004.','A law firm in Heliopolis, Cairo, founded in 2004.'))
 +sec('',x('من نحن','Who we are'),`<div class="split"><div class="rv"><p>${x('المؤسسة القانونية الدولية I.L.F مؤسسة محاماة تأسست عام 2004 على يد د. هشام الحناوي وشركاه. تعمل في تأسيس الشركات والعقود المحلية والدولية والتحكيم ومنازعات الاستثمار والتقاضي، وتتولى الأعمال القانونية لشركات في قطاعات منها الطاقة والمياه والعقارات والاتصالات والأمن السيبراني.','I.L.F International Legal Firm was founded in 2004 by Dr. Hesham El-Henawy and partners. It works on company formation, local and international contracts, arbitration, investment disputes and litigation, serving companies in sectors including energy, water, real estate, telecoms and cybersecurity.')}</p><p>${x('لدى المؤسسة فريق يقدّم الاستشارات والمحاماة بتعاقدات شهرية أو سنوية، ودعمًا إلكترونيًا وهاتفيًا، ويمكن تخصيص أحد أعضاء الفريق بدوام جزئي أو كلي تحت إشراف المؤسسة.','The firm’s team provides advisory and legal services under monthly or yearly retainers with online and phone support, and can assign a team member part- or full-time under the firm’s supervision.')}</p></div><div class="rv"><img src="${PHOTOS[1].src}" alt="${t(PHOTOS[1].cap)}" style="width:100%;box-shadow:0 30px 60px #0004"></div></div>`)
 +sec('alt',x('ما يميز عمل المؤسسة','What defines the firm’s work'),`<div class="flips">${[[x('كل درجات التقاضي والتحكيم','All court levels and arbitration'),x('خبرة في جميع درجات التقاضي ومراكز التحكيم الدولية والإقليمية.','Experience at every court level and in international and regional arbitration centres.')],[x('من التأسيس إلى التشغيل','From formation to operation'),x('تأسيس الشركات وتحويلها وتصفيتها وعمليات الدمج والاستحواذ.','Forming, converting and liquidating companies, and mergers and acquisitions.')],[x('دعم مستمر','Ongoing support'),x('تعاقدات شهرية وسنوية ودعم إلكتروني وهاتفي.','Monthly and yearly retainers with online and phone support.')],[x('قطاعات متنوعة','Diverse sectors'),x('طاقة ومياه وعقارات واتصالات وتقنية وزراعة وتجارة.','Energy, water, real estate, telecoms, technology, agriculture and trade.')]].map(c=>`<div class="ff rv" style="position:static;height:auto"><h3>${c[0]}</h3><p>${c[1]}</p></div>`).join('')}</div>`)
 +sec('',x('مسيرة المؤسسة والمؤسس','Our story'),tl())+cta(),
'practice-areas':()=>ph(x('الخدمات القانونية','Practice areas'),x('ثمانية مجالات، كلٌّ منها بتفاصيله وقائمة المستندات المطلوبة.','Eight areas, each with its details and the documents to prepare.'))+sec('',null,flips())+sec('alt',x('جهّز مستنداتك','Prepare your documents'),docsList())+cta(),
team:()=>ph(t(SITE.founder),x('مؤسس المؤسسة القانونية الدولية I.L.F','Founder, I.L.F International Legal Firm'))
 +sec('',null,`<div class="split"><div class="rv"><p>${x('دكتوراه في القانون الدولي العام (جامعة القاهرة 2016) برسالة عن الحماية الدولية للحق في الحياة، وماجستير في العقود والاتفاقيات الدولية والإدارية بنظام BOO/BOT/BOOT/FIDIC (جامعة طنطا 2005)، وليسانس الحقوق (جامعة الإسكندرية 2002).','Ph.D. in Public International Law (Cairo University, 2016) with a thesis on the international protection of the right to life; LL.M. in international and administrative agreements and contracts under BOO/BOT/BOOT/FIDIC (Tanta University, 2005); LL.B. (Alexandria University, 2002).')}</p></div><div>${mosaic()}</div></div>`)
 +sec('alt',x('المسيرة','Career'),tl())+sec('',x('العضويات','Memberships'),ul(MEMBERSHIPS.map(t)))
 +sec('alt',x('أبحاث ودورات','Research & training'),ul([x('رسالة الدكتوراه: «الحماية الدولية للحق في الحياة ومدى تطبيقها في النظام القانوني المصري» (2016)','Doctoral thesis: international protection of the right to life and its application in Egyptian law (2016)'),x('بحث «الاعتراف بالدولة» (جامعة طنطا 2004) وبحث «امتيازات السلطة التنفيذية» (2005)','Papers: “Recognition of States” (Tanta, 2004) and “Prerogatives of the executive authority” (2005)'),x('بحث عن تطبيق التحكيم في مصر مقارنةً بالقضاء، قُدّم لنقابة المحامين (2006)','Paper on arbitration in Egypt compared with the courts, submitted to the Bar Association (2006)'),x('دورات في التحكيم الدولي: مركز القاهرة الإقليمي (2005)، مركز التحكيم بجامعة عين شمس (2008)، ونقابة المحامين','Courses in international arbitration: Cairo Regional Centre (2005), Ain Shams arbitration centre (2008), Bar Association')]))
 +sec('',x('مناصب استشارية','Advisory roles'),ul(ROLES.map(t)))+cta(),
experience:()=>ph(x('الخبرات','Experience'),x('من واقع بيانات المؤسسة المعلنة.','Based on the firm’s published records.'))
 +sec('',x('شركات تولّى المكتب تأسيسها وأعمالها القانونية','Companies formed and served by the firm'),FORMED.map(f=>`<div class="yr rv"><b>${f.y}</b>${ul(f.n.map(co))}</div>`).join(''))
 +sec('alt',x('مستشار قانوني ومحامٍ منذ 2013','Legal adviser and counsel since 2013'),ul(ADVISED.map(co)))
 +sec('',x('مناصب استشارية','Advisory roles'),ul(ROLES.map(t)))
 +sec('alt',x('النتائج','Results'),`<p>${x('وفق بيانات المؤسسة: تنفيذ أحكام قضائية لعملائها منذ 2005 بلغت المبالغ المحصّلة فيها أكثر من 90 مليون جنيه مصري و6.5 مليون دولار.','According to the firm: since 2005 it has enforced judgments for clients, with sums collected exceeding EGP 90 million and USD 6.5 million.')}</p>`)+cta(),
clients:()=>ph(x('عملاء المؤسسة','Our clients'),x('اضغط على أي شعار لعرض التفاصيل.','Select a logo for details.'))+sec('dk','',ringHTML())+sec('',null,logos())+cta(),
help:()=>ph(x('مركز المساعدة القانونية','Legal help centre'),x('أدوات مجانية تساعدك على فهم موقفك وتجهيز أوراقك قبل التواصل مع المكتب.','Free tools to understand your position and prepare before contacting the firm.'))
 +sec('',null,`<div class="tabs" role="tablist">${[['wiz',x('ما مسألتك؟','Your matter')],['road',x('خارطة تأسيس شركة','Company roadmap')],['cc',x('قائمة مراجعة عقد','Contract checklist')],['faq',x('أسئلة شائعة','FAQ')],['gl',x('مسرد المصطلحات','Glossary')]].map((a,i)=>`<button role="tab" data-tab="${a[0]}" aria-selected="${i===0}">${a[1]}</button>`).join('')}</div>
 <div id="tab-wiz" class="tp"></div>
 <div id="tab-road" class="tp" hidden><h3>${x('خطوات تأسيس شركة في مصر','Steps to form a company in Egypt')}</h3><ul class="chk">${K.ROAD[L].map(s=>`<li><label><input type="checkbox">${s}</label></li>`).join('')}</ul><p class="note">${x('خطوات عامة؛ الاشتراطات تتغير ويؤكدها المحامي لنشاطك.','General steps; requirements change and a lawyer confirms them for your activity.')}</p><button class="btn" onclick="print()">${x('طباعة القائمة','Print')}</button> <a class="btn ghost" style="color:var(--navy)" href="contact.html?cat=corp">${x('اطلب مساعدة في التأسيس','Get help forming a company')}</a></div>
 <div id="tab-cc" class="tp" hidden><h3>${x('ماذا يتضمن العقد التجاري الجيد؟','What a sound commercial contract contains')}</h3><ul class="chk">${K.CCHK[L].map(s=>`<li><label><input type="checkbox">${s}</label></li>`).join('')}</ul><button class="btn" onclick="print()">${x('طباعة القائمة','Print')}</button> <a class="btn ghost" style="color:var(--navy)" href="contact.html?cat=contracts">${x('اطلب مراجعة عقد','Request a contract review')}</a></div>
 <div id="tab-faq" class="tp" hidden>${['firm','founder','services','consult','fees','contact','privacy'].map(guide).join('')}</div>
 <div id="tab-gl" class="tp" hidden>${K.GLOSS.map(g=>`<details class="q"><summary>${L==='ar'?g[0]+' ('+g[1]+')':g[1]+' ('+g[0]+')'}</summary><p>${L==='ar'?g[2]:g[3]}</p></details>`).join('')}</div>`)+cta(),
'ai-assistant':()=>ph(x('المساعد القانوني الذكي','AI legal assistant'),x('يعرّفك بالمكتب وخدماته، ويرشدك قانونيًا بشكل عام، ويجهّز طلبك للمحامي.','Introduces the firm and its services, gives general legal guidance, and prepares your request for a lawyer.'))
 +sec('',null,`<div class="aigrid"><div data-chat></div><aside class="side"><h3>${x('جرّب أن تسأل','Try asking')}</h3>${[x('كيف أؤسس شركة؟','How do I form a company?'),x('ماذا يجب أن يتضمن العقد التجاري؟','What should a commercial contract include?'),x('ما الفرق بين التحكيم والقضاء؟','Arbitration vs court?'),x('ما خدمات المكتب؟','What are the firm’s services?'),x('كيف أحجز استشارة؟','How do I book a consultation?')].map(q=>`<button data-ask="${q}">${q}</button>`).join('')}<p class="note" style="margin-top:1rem">${x('الردود العامة لا تغني عن محامٍ يطّلع على أوراقك. في الحالات العاجلة اتصل على','General answers are no substitute for a lawyer reviewing your papers. In urgent cases call')} <a href="tel:${SITE.phone}" dir="ltr">${SITE.phone}</a></p></aside></div>`),
insights:()=>ph(x('أدلة ومقالات قانونية','Legal guides & articles'),x('أدلة تعريفية عامة. المقالات التي يعتمدها المكتب ستُضاف هنا.','General guides. Articles approved by the firm will be added here.'))
 +sec('',null,`<div class="f"><label for="gs">${x('ابحث في الأدلة','Search guides')}</label><input id="gs"></div><div id="gl2">${['company','contract','arbitration','investment','banking','litigation','tech','retainer'].map(guide).join('')}</div><p class="note">${x('المحتوى تثقيفي عام ولا يغني عن استشارة قانونية خاصة بحالتك، وهو قيد مراجعة المكتب.','Educational content is not a substitute for case-specific legal advice and is pending review by the firm.')}</p>`)+cta(),
contact:()=>ph(x('تواصل واطلب استشارة','Contact & consultation'))+sec('',null,`<div class="cg"><div class="rv"><p>${t(SITE.address)}</p><p><a href="tel:${SITE.phone}" dir="ltr">${SITE.phone}</a></p><p><a href="${WA()}" target="_blank" rel="noopener">${x('واتساب','WhatsApp')}</a></p><p><a href="mailto:${SITE.email}">${SITE.email}</a></p><p><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(SITE.address.ar)}" target="_blank" rel="noopener">${x('افتح العنوان في خرائط جوجل','Open address in Google Maps')}</a></p></div>
 <form id="cf" class="form" novalidate><div class="f"><label for="name">${x('الاسم بالكامل','Full name')}</label><input id="name" name="name" autocomplete="name"><small data-e="name"></small></div>
 <div class="two"><div class="f"><label for="method">${x('وسيلة التواصل','Preferred contact')}</label><select id="method" name="method"><option value="phone">${x('هاتف / واتساب','Phone / WhatsApp')}</option><option value="email">${x('بريد إلكتروني','Email')}</option></select></div><div class="f"><label for="contact">${x('الهاتف أو البريد','Phone or email')}</label><input id="contact" name="contact"><small data-e="contact"></small></div></div>
 <div class="two"><div class="f"><label for="cat">${x('نوع المسألة','Matter type')}</label><select id="cat" name="cat">${AREAS.map(a=>`<option value="${a.id}">${t(a.t)}</option>`).join('')}<option value="other">${x('أخرى','Other')}</option></select></div><div class="f"><label for="plang">${x('اللغة المفضلة','Language')}</label><select id="plang" name="lang"><option value="ar">العربية</option><option value="en">English</option></select></div></div>
 <div class="f"><label for="msg">${x('وصف موجز','Brief description')}</label><textarea id="msg" name="msg" rows="4" maxlength="2000"></textarea><small data-e="msg"></small></div><p class="note">${x('لا تُدرج كلمات مرور أو بيانات مالية.','Do not include passwords or financial credentials.')}</p>
 <label class="ck"><input type="checkbox" name="consent">${x('أوافق على استخدام بياناتي للرد على طلبي فقط.','I agree my details are used only to respond to my request.')}</label><small data-e="consent"></small><p id="fs" class="er" role="alert" hidden></p><button type="submit">${x('اطلب استشارة','Request consultation')}</button></form></div>`)
};
// ---------- shell ----------
let ringRaf=0;
const mqD=matchMedia('(min-width:1200px)'),syncMenu=()=>{const m=$('.menu');if(m)m.open=mqD.matches};
if(mqD.addEventListener)mqD.addEventListener('change',syncMenu);
function shell(){
 document.documentElement.lang=L;document.documentElement.dir=L==='ar'?'rtl':'ltr';cancelAnimationFrame(ringRaf);
 const cur=NAV.find(n=>(n[0]||'home')===page);document.title=(cur&&page!=='home'?t(cur[1])+' | ':'')+t(SITE.name);
 $('#nav').innerHTML=`<a class="skip" href="#m">${x('تخطَّ إلى المحتوى','Skip to content')}</a><nav class="nav" aria-label="${x('التنقل الرئيسي','Main navigation')}"><div class="wrap"><a href="index.html" class="logo"><i><b>IL</b></i><span>${t(SITE.name)}</span></a><div class="navr"><button type="button" id="lang" class="langbtn" aria-label="${x('Switch to English','التبديل إلى العربية')}" title="${x('English','العربية')}"><b class="${L==='ar'?'on':''}" lang="ar">ع</b><b class="${L==='en'?'on':''}" lang="en">EN</b></button><details class="menu"><summary>${x('القائمة','Menu')}</summary><div>${NAV.map(n=>`<a href="${href(n[0])}"${(n[0]||'home')===page?' aria-current="page"':''}>${t(n[1])}</a>`).join('')}</div></details></div></div></nav>`;
 $('#m').innerHTML=V[page]();
 $('#foot').innerHTML=`<footer><div class="wrap"><div><h3>${t(SITE.name)}</h3><p>${t(SITE.address)}</p><p class="note">${x('المعلومات في هذا الموقع عامة ولا تُعد استشارة قانونية ولا تنشئ علاقة موكّل ومحامٍ.','Information on this site is general, is not legal advice and creates no attorney-client relationship.')}</p></div><div><h3>${x('روابط','Links')}</h3>${NAV.slice(0,6).map(n=>`<a href="${href(n[0])}">${t(n[1])}</a>`).join('')}</div><div><h3>${x('تواصل','Contact')}</h3><a href="tel:${SITE.phone}" dir="ltr">${SITE.phone}</a><a href="${WA()}" target="_blank" rel="noopener">WhatsApp</a><a href="mailto:${SITE.email}">${SITE.email}</a></div></div></footer>
 <div class="fab"><a class="wa" href="${WA()}" target="_blank" rel="noopener">WhatsApp</a>${page==='ai-assistant'?'':`<button data-open-ai>${x('اسأل المساعد','Ask the assistant')}</button>`}</div><div id="pnl"></div>`;
 if(page==='ai-assistant')mountChat($('[data-chat]'));
 initGal();initRing();initReveal();wiz();prefill();syncMenu();
}
// ---------- reveal / counters / tilt ----------
function initReveal(){const io='IntersectionObserver' in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12}):null;$$('.rv').forEach(el=>io?io.observe(el):el.classList.add('in'));
 const co=io&&new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;co.unobserve(e.target);const to=+e.target.dataset.to;if(red)return;const t0=performance.now();(function f(n){const p=Math.min((n-t0)/1200,1);e.target.textContent=Math.round(to*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(f)})(t0)}));$$('.num').forEach(n=>{if(co&&!red){n.textContent='0';co.observe(n)}})}
let cur=null;document.addEventListener('pointermove',e=>{if(!matchMedia('(hover:hover)').matches||red)return;const el=e.target.closest&&e.target.closest('.tilt');if(cur&&cur!==el)cur.style.transform='';cur=el;if(!el)return;const r=el.getBoundingClientRect(),px=(e.clientX-r.left)/r.width-.5,py=(e.clientY-r.top)/r.height-.5;el.style.transform=`rotateY(${px*14}deg) rotateX(${-py*14}deg)`});
// ---------- modal ----------
let lb=false;
function modal(h){closeM();const o=document.createElement('div');o.className='ov';o.innerHTML=`<div class="dlg" role="dialog" aria-modal="true"><button class="x" aria-label="Close">×</button>${h}</div>`;document.body.appendChild(o);document.body.style.overflow='hidden';o.querySelector('.x').focus()}
function closeM(){const o=$('.ov');if(o)o.remove();document.body.style.overflow='';lb=false}
// ---------- gallery ----------
let gi=0,timer=null,sx=0;const n=PHOTOS.length;
function updGal(){$$('.gal').forEach(g=>{g.querySelectorAll('.slide').forEach((s,k)=>{let r=k-gi;if(r>n/2)r-=n;if(r<-n/2)r+=n;const a=Math.abs(r);s.style.transform=`translateX(${r*52}%) rotateY(${-r*26}deg) scale(${1-a*.16})`;s.style.zIndex=9-a;s.style.opacity=a>1?0:1-a*.35;s.tabIndex=a?-1:0});g.querySelectorAll('.dots i').forEach((d,k)=>d.className=k===gi?'on':'');g.querySelector('#cap').textContent=t(PHOTOS[gi].cap);const p=g.querySelector('#play');p.textContent=timer?x('إيقاف التشغيل التلقائي','Pause autoplay'):x('تشغيل تلقائي','Autoplay');p.setAttribute('aria-pressed',!!timer)});
 if(lb){const i=$('.dlg .big');if(i){i.src=PHOTOS[gi].src;i.alt=t(PHOTOS[gi].cap);$('.dlg .lc').textContent=t(PHOTOS[gi].cap)}}}
function go(d){gi=(gi+d+n)%n;updGal()}
function initGal(){if(!$('.gal')){clearInterval(timer);timer=null;return}updGal()}
// ---------- 3D ring ----------
let impulse=0;
function initRing(){const el=$('.ring');if(!el)return;const it=[...el.children],N=it.length,R=Math.max(250,Math.round(210*N/(2*Math.PI)*1.3));let ang=0,drag=false,px=0,moved=0;
 it.forEach((b,i)=>b.style.transform=`rotateY(${i*360/N}deg) translateZ(${R}px)`);const w=$('.ringw');
 w.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;moved=0});addEventListener('pointerup',()=>drag=false);
 addEventListener('pointermove',e=>{if(!drag)return;const d=e.clientX-px;px=e.clientX;moved+=Math.abs(d);ang+=d*.35});
 w.addEventListener('click',e=>{if(moved>6){e.stopPropagation();e.preventDefault();moved=0}},true);
 let hov=false;w.addEventListener('pointerenter',()=>hov=true);w.addEventListener('pointerleave',()=>hov=false);
 (function tick(){if(!drag&&!red&&!hov)ang+=.18;ang+=impulse;impulse*=.92;el.style.transform=`translateZ(${-R}px) rotateY(${ang}deg)`;ringRaf=requestAnimationFrame(tick)})()}
// ---------- help wizard ----------
let wz=null,urg=null;
function wiz(){const el=$('#tab-wiz');if(!el)return;
 if(!wz){el.innerHTML=`<h3>${x('ما نوع مسألتك؟','What kind of matter is it?')}</h3><div class="cats">${AREAS.map(a=>`<button data-cat="${a.id}"><b>${t(a.t)}</b><br><small style="color:inherit;opacity:.7">${t(a.s)}</small></button>`).join('')}</div>`;return}
 const a=AREAS.find(a=>a.id===wz),e=K.entries.find(e=>e.cat===wz);
 el.innerHTML=`<button class="lnk" data-cat="">‹ ${x('رجوع','Back')}</button><div class="res"><h3>${t(a.t)}</h3><p>${e?e.a[L]:t(a.s)}</p><h3 style="font-size:1.15rem">${x('ما الذي تجهّزه؟','What to prepare')}</h3>${ul(K.DOCS[wz][L])}${e&&e.f[L].length?`<h3 style="font-size:1.15rem">${x('أسئلة سيطرحها المحامي','Questions the lawyer will ask')}</h3>${ul(e.f[L])}`:''}
 <h3 style="font-size:1.15rem">${x('هل هناك موعد أو جلسة خلال أيام قليلة؟','Is there a deadline or hearing within days?')}</h3><div class="row"><button class="btn ghost" style="color:var(--navy)" data-urg="1">${x('نعم','Yes')}</button><button class="btn ghost" style="color:var(--navy)" data-urg="0">${x('لا','No')}</button></div>
 ${urg==='1'?`<div class="ur" role="alert">${x('الأمر عاجل: اتصل بالمكتب الآن','This is urgent: call the firm now')} <a href="tel:${SITE.phone}" dir="ltr"><b>${SITE.phone}</b></a> · <a href="${WA(t(a.t))}" target="_blank" rel="noopener">WhatsApp</a></div>`:''}
 <div class="row" style="margin-top:1rem"><a class="btn" href="contact.html?cat=${wz}">${x('اطلب استشارة','Request a consultation')}</a><button class="btn ghost" style="color:var(--navy)" data-ask="${t(a.t)}">${x('اسأل المساعد عن هذا المجال','Ask the assistant about this')}</button></div></div>`}
// ---------- chat ----------
let msgs=[],busy=false,consent=(()=>{try{return localStorage.getItem('aiConsent')==='1'}catch(e){return false}})(),cid=uid();
const starters=()=>L==='ar'?['ما خدمات المكتب؟','كيف أؤسس شركة؟','عندي سؤال عن عقد','أريد حجز استشارة','ما الفرق بين التحكيم والقضاء؟']:['What services do you offer?','How do I form a company?','I have a contract question','I want to book a consultation','Arbitration vs court?'];
const chatShell=()=>`<div class="cw" data-chat-in><div class="ch"><span class="orb"></span><div><b>${x('مساعد I.L.F','I.L.F assistant')}</b><small>${x('مساعد آلي، ليس محاميًا','Automated assistant, not a lawyer')}</small></div><button data-act="new">${x('محادثة جديدة','New chat')}</button></div>
 <p class="note">${x('معلومات عامة فقط، ولا تنشئ علاقة موكّل ومحامٍ. لا ترسل كلمات مرور أو بيانات مالية.','General information only; creates no attorney-client relationship. Never send passwords or financial data.')}</p>
 <div class="msgs" aria-live="polite"></div><div class="chips"></div><p class="er" role="alert" hidden style="padding:0 1rem"></p>
 <label class="ck"><input type="checkbox" data-consent ${consent?'checked':''}>${x('أسمح بإرسال رسائلي لخدمة المساعد الذكي لردود موسّعة (وإلا أُجيب من دليل المكتب داخل متصفحك).','Allow sending my messages to the AI service for fuller answers (otherwise I answer from the firm guide inside your browser).')}</label>
 <div class="in"><input maxlength="1500" placeholder="${x('اكتب سؤالك هنا','Type your question')}" aria-label="${x('رسالتك','Your message')}"><button data-act="send">${x('إرسال','Send')}</button></div></div>`;
function mountChat(host){host.innerHTML=chatShell();draw()}
const root=()=>$('[data-chat-in]');
function md(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/\*\*(.+?)\*\*/g,'<b>$1</b>').replace(/^[-•] (.+)$/gm,'• $1').replace(/\n/g,'<br>')}
function draw(){const r=root();if(!r)return;const box=r.querySelector('.msgs');box.textContent='';
 if(!msgs.length){const p=document.createElement('p');p.className='b a';p.textContent=x('أهلًا بك. أعرّفك بالمكتب وخدماته، وأرشدك قانونيًا بشكل عام، وأجهّز طلبك للمحامي. اختر سؤالًا أو اكتب مسألتك.','Welcome. I introduce the firm and its services, give general legal guidance and prepare your request for a lawyer. Pick a question or describe your matter.');box.appendChild(p)}
 msgs.forEach(m=>{const p=document.createElement('p');p.className='b '+m.r;if(m.r==='a'&&m.src){const g=document.createElement('span');g.className='tag';g.textContent=m.src==='ai'?x('مساعد ذكي (رد آلي)','AI assistant (automated)'):x('من دليل المكتب','From the firm guide');p.appendChild(g)}
  if(m.src==='ai'){const d=document.createElement('span');d.innerHTML=md(m.x);p.appendChild(d)}else p.appendChild(document.createTextNode(m.x));box.appendChild(p)});
 if(busy){const p=document.createElement('p');p.className='b a dots2';p.innerHTML='<i></i><i></i><i></i>';box.appendChild(p)}box.scrollTop=box.scrollHeight;
 const ch=r.querySelector('.chips');ch.textContent='';const lastA=[...msgs].reverse().find(m=>m.r==='a');
 const add=(l,a)=>{const e=document.createElement(a.href?'a':'button');e.textContent=l;if(a.href){e.href=a.href;if(a.ext){e.target='_blank';e.rel='noopener'}}else e.dataset.ask=a.q;ch.appendChild(e)};
 if(!msgs.length)starters().forEach(q=>add(q,{q}));else if(lastA&&!busy){(lastA.fu||[]).forEach(q=>add(q,{q}));add(x('اطلب استشارة','Request consultation'),{href:'contact.html'+(lastA.cat?'?cat='+lastA.cat:'')});add('WhatsApp',{href:WA(msgs.filter(m=>m.r==='u').slice(-1)[0].x),ext:1})}}
function er(m,h){const e=root().querySelector('.er');e.hidden=!m;e.textContent=m||'';e.style.color=h?'inherit':''}
async function post(url,body){const ac=new AbortController(),to=setTimeout(()=>ac.abort(),25000);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:ac.signal});if(!r.ok)throw new Error('http');const tx=await r.text();try{return JSON.parse(tx)}catch(e){return{reply:tx}}}finally{clearTimeout(to)}}
async function send(text){text=(text||'').trim();if(!text||busy||!root())return;er('');busy=true;const hist=msgs.slice(-10).map(m=>({r:m.r,x:m.x}));msgs.push({r:'u',x:text});draw();let ok=false,failed=false;
 if(consent&&cfg.CHAT_ENDPOINT){try{const j=await post(cfg.CHAT_ENDPOINT,{type:'chat',conversationId:cid,message:text,lang:L,consent:true,history:hist}),jj=Array.isArray(j)?j[0]:j,r=jj&&(jj.reply||jj.output||jj.text||jj.message||(jj.data&&jj.data.reply));if(typeof r==='string'&&r.trim()){msgs.push({r:'a',x:r,src:'ai'});ok=true}else failed=true}catch(e){failed=true}}
 if(!ok){await new Promise(r=>setTimeout(r,350));const a=K.answer(text,L);
  if(failed&&root())er(x('تعذّر الاتصال بالمساعد الذكي، فأجبتك من دليل المكتب.','Could not reach the AI service, so I answered from the firm guide.'));
  if(a)msgs.push({r:'a',x:a.x,src:'kb',fu:a.f,cat:a.cat});else msgs.push({r:'a',x:x('لم أجد إجابة دقيقة لهذا السؤال في دليل المكتب، والأفضل أن يراجعه محامٍ. يمكنك طلب استشارة أو مراسلة المكتب على واتساب، أو اختيار موضوع من الأسفل.','I could not find a precise answer in the firm guide, and a lawyer should review it. You can request a consultation, message the firm on WhatsApp, or pick a topic below.'),src:'kb',fu:starters().slice(0,3)})}
 if(!consent&&cfg.CHAT_ENDPOINT&&!window.__aiHint&&root()){window.__aiHint=1;er(x('لردود أوسع من المساعد الذكي، فعّل خانة الموافقة أدناه.','For fuller answers from the AI assistant, tick the consent box below.'),1)}
 busy=false;draw()}
function openAI(q){if(page==='ai-assistant'){if(q)send(q);return}let p=$('#pnl');if(!p.firstChild){p.innerHTML='<div class="panel"></div>';mountChat(p.firstChild)}if(q)send(q)}
// ---------- prefill / events ----------
function prefill(){const c=new URLSearchParams(location.search).get('cat'),s=$('#cat');if(c&&s&&[...s.options].some(o=>o.value===c))s.value=c}
document.addEventListener('click',e=>{const T=e.target,c=s=>T.closest(s);let m;
 if(c('#lang.langbtn')){e.preventDefault();const nl=L==='ar'?'en':'ar';try{localStorage.setItem('lang',nl)}catch(_){}try{const u=new URL(location.href);u.searchParams.set('lang',nl);location.replace(u.toString())}catch(_){location.search='?lang='+nl}return}
 if(m=c('.flip')){m.classList.toggle('on');return}
 if(m=c('[data-g]')){go(+m.dataset.g);return}
 if(m=c('.mz')){gi=+m.dataset.k;lb=true;modal(`<img class="big" src="${PHOTOS[gi].src}" alt="${t(PHOTOS[gi].cap)}"><div class="gc" dir="ltr"><button data-g="-1" aria-label="Previous">‹</button><span class="lc">${t(PHOTOS[gi].cap)}</span><button data-g="1" aria-label="Next">›</button></div>`);return}
 if(m=c('.slide')){const k=+m.dataset.k;if(k===gi){lb=true;modal(`<img class="big" src="${PHOTOS[gi].src}" alt="${t(PHOTOS[gi].cap)}"><div class="gc" dir="ltr"><button data-g="-1" aria-label="Previous">‹</button><span class="lc">${t(PHOTOS[gi].cap)}</span><button data-g="1" aria-label="Next">›</button></div>`)}else{gi=k;updGal()}return}
 if(T.id==='play'){if(timer){clearInterval(timer);timer=null}else if(!red)timer=setInterval(()=>go(1),4500);updGal();return}
 if(m=c('[data-spin]')){impulse+=+m.dataset.spin*-5;return}
 if(m=c('[data-id]')){const k=CLIENTS.find(k=>k.id===m.dataset.id);modal(`<img class="lg" src="${k.logo}" alt="${t(k.n)}"><h3>${t(k.n)}</h3><dl><dt>${x('العلاقة','Relationship')}</dt><dd>${t(k.rel)}</dd>${t(k.ind)?`<dt>${x('المجال','Field')}</dt><dd>${t(k.ind)}</dd>`:''}</dl>`);return}
 if(T.classList.contains('x')||T.classList.contains('ov')){closeM();return}
 if(m=c('[data-tab]')){$$('[data-tab]').forEach(b=>b.setAttribute('aria-selected',b===m));$$('.tp').forEach(p=>p.hidden=p.id!=='tab-'+m.dataset.tab);return}
 if(m=c('[data-cat]')){wz=m.dataset.cat||null;urg=null;wiz();return}
 if(m=c('[data-urg]')){urg=m.dataset.urg;wiz();return}
 if(c('[data-open-ai]')){openAI();return}
 if(m=c('[data-ask]')){openAI(m.dataset.ask);if(page!=='ai-assistant'&&c('#tab-wiz,.side'))return;return}
 if(m=c('[data-act]')){if(m.dataset.act==='send'){const i=root().querySelector('input[type=text],input:not([type])');send(i.value);i.value=''}if(m.dataset.act==='new'){msgs=[];cid=uid();draw();er('')}}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-consent]'))consent=e.target.checked;try{localStorage.setItem('aiConsent',consent?'1':'0')}catch(_){}document.querySelectorAll('[data-consent]').forEach(c=>c.checked=consent)});
document.addEventListener('input',e=>{if(e.target.id==='gs'){const q=e.target.value.toLowerCase();$$('#gl2 details').forEach(d=>d.hidden=q&&!d.textContent.toLowerCase().includes(q))}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeM();
 if(e.key==='Enter'&&e.target.closest&&e.target.closest('[data-chat-in]')&&e.target.tagName==='INPUT'&&e.target.type!=='checkbox'){send(e.target.value);e.target.value=''}
 if(e.key==='Enter'&&e.target.classList&&e.target.classList.contains('flip'))e.target.classList.toggle('on');
 if((lb||(e.target.closest&&e.target.closest('.gal')))&&(e.key==='ArrowRight'||e.key==='ArrowLeft'))go(e.key==='ArrowRight'?1:-1)});
document.addEventListener('touchstart',e=>{if(e.target.closest('.stage'))sx=e.touches[0].clientX},{passive:true});
document.addEventListener('touchend',e=>{if(e.target.closest('.stage')){const d=e.changedTouches[0].clientX-sx;if(Math.abs(d)>40)go(d<0?1:-1)}});
document.addEventListener('submit',async e=>{if(e.target.id!=='cf')return;e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f)),er2={},fs=$('#fs'),btn=f.querySelector('button[type=submit]');if(btn.disabled)return;
 if(!(d.name||'').trim())er2.name=x('اكتب اسمك','Enter your name');
 if(d.method==='email'?!/^\S+@\S+\.\S+$/.test(d.contact||''):!/^[+\d][\d\s-]{7,}$/.test(d.contact||''))er2.contact=x('بيانات التواصل غير صحيحة','Invalid contact detail');
 if((d.msg||'').trim().length<10)er2.msg=x('اشرح طلبك في 10 أحرف على الأقل','Describe your request (10+ characters)');
 if(!d.consent)er2.consent=x('الموافقة مطلوبة','Consent is required');
 f.querySelectorAll('[data-e]').forEach(s=>s.textContent=er2[s.dataset.e]||'');fs.hidden=true;if(Object.keys(er2).length)return;
 btn.disabled=true;btn.textContent=x('جارٍ الإرسال…','Sending…');const url=cfg.LEADS_ENDPOINT||cfg.CHAT_ENDPOINT,cat=(AREAS.find(a=>a.id===d.cat)||{t:{ar:'أخرى',en:'Other'}}).t;
 try{if(!url)throw 0;await post(url,{type:'consultation',lang:L,consent:true,intake:{name:d.name,method:d.method,contact:d.contact,category:t(cat),language:d.lang,description:d.msg}});f.outerHTML=`<p class="okm" role="status">${x('تم استلام طلبك. سيتواصل معك المكتب.','Your request was received. The firm will contact you.')}</p>`}
 catch(_){fs.hidden=false;fs.innerHTML=x('لم يُرسل طلبك. أرسله مباشرة عبر ','Your request was NOT sent. Send it directly via ')+`<a href="${WA(`${d.name}\n${t(cat)}\n${d.msg}`)}" target="_blank" rel="noopener">WhatsApp</a>`;btn.disabled=false;btn.textContent=x('اطلب استشارة','Request consultation')}});
shell();
})();
